#!/usr/bin/env python3
"""dump_enhy_body_table.py — extract EnHy's per-type body-color + object-id tables
from the OoT3D binary and emit a C .inc file usable by the SoH3D port.

Ground truth: `EnHy_Draw` (VA 0x001b4944) reads two tables from a literal pool
just after the function body. The Ghidra decomp (build/decomp/001b4944.c) shows:

    iVar4 = DAT_001b4c70 + -0x348;
    sVar2 = *(short *)(DAT_001b4c70 + uVar3 * 0x18);   -> object-id table
    ...
    *(char *)(iVar4 + uVar3 * 0x28)                    -> color-override table

`DAT_001b4c70` is NOT the table address — it's a literal-pool entry that HOLDS
the table's real address (little-endian u32). Reading code.bin @ 0x1b4c70:

    u32 @ 0x1b4c70 = 0x00527a4c   <- object-id table start
    obj_row_size   = 0x18         (first u16 = OBJECT id, rest = per-archetype junk)
    color_table    = 0x00527a4c - 0x348 = 0x00527704
    color_row_size = 0x28

Color row layout (from the switch at 0x1b4b10, ports through
FUN_00357a50 = Model_SetMaterialConstantColor(model, matIdx, constIdx, rgba, 1)):

    +0x00  s8   pre       (BOJ/AHG/CNE: material to reset before overrides; -1 skip)
    +0x01  s8   pre2      (BOB path only; -1 skip)
    +0x02  s8   matA      (target material for constant 4 override; -1 skip)
    +0x03  s8   matB      (target material for constant 3 override; -1 skip)
    +0x04  f32[4] colorA  (RGBA float, applied to matA's constant 4)
    +0x14  f32[4] colorB  (RGBA float, applied to matB's constant 3)
    +0x24  u32  trail     (per-type index/hash — appears to be an unrelated pool entry)

Types 0x00, 0x01, 0x06, 0x12 have matA/matB = -1 → default palette (no override).
Cases 8 and 0xB have additional constant-2 overrides from other pool entries
(DAT_001b4c74/DAT_001b4c78) — not covered here (handle at port time).

Verify: `code.bin` first byte maps to VA 0x00100000 (see extract_code.py header).
"""
from __future__ import annotations
import argparse
import os
import struct
import sys

CODE_BIN = os.path.join(os.path.dirname(__file__), "..", "build", "code.bin")
BASE_VA = 0x00100000

# Ghidra literal-pool holding the OBJECT-id table address.
LIT_POOL_OBJ = 0x001B4C70
COLOR_TBL_DELTA = -0x348           # per decomp: iVar4 = objTblAddr + -0x348
OBJ_ROW_SIZE = 0x18
COLOR_ROW_SIZE = 0x28
NUM_TYPES = 22                     # switch(uVar3) covers 0..0x14; type 0x15 exists in-table but is trailing pad

OBJECT_NAMES = {
    0x0105: "OBJECT_HY_TYPE_0105",   # unknown / boss-specific NPC; -1 skip row
    0x018C: "OBJECT_HY_TYPE_018C",
    0x0107: "OBJECT_AHG",            # adult human general
    0x0108: "OBJECT_BOJ",            # adult male townsman variant
    0x0109: "OBJECT_BOB_CHILD",
    0x010C: "OBJECT_CNE",            # adult woman
    0x010D: "OBJECT_HY_TYPE_010D",
    0x0111: "OBJECT_BOB",             # child variant
    0x0115: "OBJECT_HY_TYPE_0115",
}


def load_code_bin(path: str) -> bytes:
    with open(path, "rb") as f:
        return f.read()


def at(va: int) -> int:
    return va - BASE_VA


def read_tables(b: bytes):
    obj_tbl = struct.unpack_from("<I", b, at(LIT_POOL_OBJ))[0]
    color_tbl = obj_tbl + COLOR_TBL_DELTA
    rows = []
    for t in range(NUM_TYPES):
        objo = at(obj_tbl) + t * OBJ_ROW_SIZE
        colo = at(color_tbl) + t * COLOR_ROW_SIZE
        obj_id = struct.unpack_from("<H", b, objo)[0]
        pre, pre2, matA, matB = struct.unpack_from("<bbbb", b, colo)
        cA = struct.unpack_from("<4f", b, colo + 0x04)
        cB = struct.unpack_from("<4f", b, colo + 0x14)
        rows.append((t, obj_id, pre, pre2, matA, matB, cA, cB))
    return obj_tbl, color_tbl, rows


def emit_inc(obj_tbl_va: int, color_tbl_va: int, rows, out):
    out.write("// GENERATED by tools/dump_enhy_body_table.py — DO NOT EDIT BY HAND.\n")
    out.write("//\n")
    out.write(f"// Source: OoT3D USA .code, object-id table @ VA 0x{obj_tbl_va:08x},\n")
    out.write(f"//         body-color override table @ VA 0x{color_tbl_va:08x},\n")
    out.write("//         consumed by EnHy_Draw (0x001b4944).\n")
    out.write("//\n")
    out.write("// See docs/enhy_body_colors.md for the row layout + semantics.\n")
    out.write("\n")
    out.write("#include <stdint.h>\n\n")
    out.write("typedef struct {\n")
    out.write("    uint16_t objectId;    // OoT3D OBJECT_* id for the archetype\n")
    out.write("    int8_t   pre;          // reset material index before overrides (-1 = skip)\n")
    out.write("    int8_t   pre2;         // BOB-path reset (-1 = skip)\n")
    out.write("    int8_t   matA;         // target material index for constant-4 override (-1 = skip)\n")
    out.write("    int8_t   matB;         // target material index for constant-3 override (-1 = skip)\n")
    out.write("    float    colorA[4];    // RGBA float applied to (matA, constant 4)\n")
    out.write("    float    colorB[4];    // RGBA float applied to (matB, constant 3)\n")
    out.write("} EnHyBodyColorEntry;\n\n")
    out.write(f"#define EN_HY_BODY_COLOR_COUNT {len(rows)}\n\n")
    out.write("static const EnHyBodyColorEntry kEnHyBodyColorTable[EN_HY_BODY_COLOR_COUNT] = {\n")
    for (t, obj, pre, pre2, mA, mB, cA, cB) in rows:
        name = OBJECT_NAMES.get(obj, "OBJECT_UNKNOWN")
        out.write(f"    /* type 0x{t:02x} */ {{ 0x{obj:04x}, {pre:>3}, {pre2:>3}, {mA:>3}, {mB:>3},\n")
        out.write(f"        {{ {cA[0]:.6f}f, {cA[1]:.6f}f, {cA[2]:.6f}f, {cA[3]:.6f}f }},\n")
        out.write(f"        {{ {cB[0]:.6f}f, {cB[1]:.6f}f, {cB[2]:.6f}f, {cB[3]:.6f}f }} }}, // {name}\n")
    out.write("};\n")


def emit_human(rows, out):
    out.write(
        f"{'type':>4} | {'object':<27} | pre pre2 matA matB | "
        f"{'colorA (R G B A)':<38} | {'colorB (R G B A)':<38}\n"
    )
    out.write("-" * 130 + "\n")
    for (t, obj, pre, pre2, mA, mB, cA, cB) in rows:
        name = OBJECT_NAMES.get(obj, f"OBJECT_UNKNOWN_0x{obj:04x}")
        cAs = "(" + " ".join(f"{v:.3f}" for v in cA) + ")"
        cBs = "(" + " ".join(f"{v:.3f}" for v in cB) + ")"
        out.write(
            f" 0x{t:02x} | 0x{obj:04x} {name:<22} | "
            f"{pre:>3} {pre2:>3} {mA:>3} {mB:>3} | "
            f"{cAs:<38} | {cBs:<38}\n"
        )


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--code-bin", default=CODE_BIN)
    ap.add_argument("--out", help="write generated C .inc to this path (else stdout)")
    ap.add_argument("--human", action="store_true", help="human-readable table dump instead of C")
    args = ap.parse_args()

    b = load_code_bin(args.code_bin)
    obj_tbl, color_tbl, rows = read_tables(b)

    sink = open(args.out, "w") if args.out else sys.stdout
    try:
        if args.human:
            emit_human(rows, sink)
        else:
            emit_inc(obj_tbl, color_tbl, rows, sink)
    finally:
        if args.out:
            sink.close()


if __name__ == "__main__":
    main()
